[package]
name = "mithril"
version = "0.1.0"
authors = [
    # Feel free to add yourself here
    "Felix Wiegand <felix-wiegand@protonmail.ch>"
]
edition = "2021"

[[test]]
name = "telemetry"
harness = false

[lib]
harness = false

[dependencies]
static_cell = { version = "1.1", features = ["nightly"]}
num-traits = { version = "0.2.15", default-features = false }
nb = "1"
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
postcard = "1.0"
crc = "3"
ahrs = { git = "https://github.com/KoffeinFlummi/ahrs-rs", default-features = false }
nalgebra = { version = "0.31", default-features = false, features = ["alloc", "serde-serialize-no-std"] }
filter = { git = "https://github.com/KoffeinFlummi/filter-rs" }
ublox = { version = "=0.4.2", default-features = false }
siphasher = { version = "0.3", default-features = false }
rand = { version = "0.8", default-features = false }
rand_chacha = { version = "0.3", default-features = false }

# Only load dependencies for embedded for the STM32 target, to avoid loading them when
# importing this crate from the groundstation on x86
[target.'cfg(target_arch = "arm")'.dependencies]
embedded-hal = { version = "=1.0.0-rc.1" }
embedded-hal-async = { version = "=1.0.0-rc.1" }

cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
alloc-cortex-m = "0.4"

# TODO: move USB fix to here, create issue
# TODO: pin embassy version
embassy-stm32        = { path = "../embassy/embassy-stm32", features = ["nightly", "unstable-traits", "defmt", "stm32f401rc", "unstable-pac", "memory-x", "time-driver-any", "exti"]  }
embassy-executor     = { path = "../embassy/embassy-executor", features = ["nightly", "arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers"] }
embassy-time         = { path = "../embassy/embassy-time", features = ["defmt", "defmt-timestamp-uptime", "unstable-traits", "tick-hz-512_000"] }
embassy-embedded-hal = { path = "../embassy/embassy-embedded-hal" }
embassy-sync         = { path = "../embassy/embassy-sync", features = ["defmt"] }
embassy-usb          = { path = "../embassy/embassy-usb", features = ["defmt"] }

defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }

[dev-dependencies]
defmt-test = "0.3"

[features]
default = ["rev2"]
rev2 = []
gcs = []

# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = 'z'         # <-
overflow-checks = true  # <-

# cargo test
[profile.test]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = 'z'         # <-
overflow-checks = true  # <-

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
lto = 'fat'
opt-level = 'z'          # <-
overflow-checks = false  # <-

# cargo test --release
[profile.bench]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
lto = 'fat'
opt-level = 'z'          # <-
overflow-checks = false  # <-
