[package]
name = "euroc_fc_firmware"
version = "0.1.0"
authors = [
    # Feel free to add yourself here
    "Felix Wiegand <felix-wiegand@protonmail.ch>"
]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "z"
lto = true

[profile.dev]
opt-level = "z"

[dependencies]
embedded-hal = "0.2"
num-traits = { version = "0.2", default-features = false }
nb = "1"
cortex-m = "0.7"
cortex-m-rt = "0.7"
alloc-cortex-m = { version = "0.4", optional = true } # Only load this for no_std, since it forces us to use nightly
panic-halt = "0.2"
panic-rtt-target = {version = "0.1.1", features = ["cortex-m"]}
rtt-target = {version = "0.3", features = ["cortex-m"]}
stm32f4xx-hal = {git = "https://github.com/stm32-rs/stm32f4xx-hal", features = ["rt", "stm32f401", "usb_fs"]}
usbd-serial = "0.1.1"
usb-device ="0.2.9"
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
postcard = "0.7.2"
crc = "2"
ahrs = { version = "0.5", default-features = false }
nalgebra = { version = "0.30", default-features = false, features = ["alloc", "serde-serialize-no-std"] }
filter = "0.2"
ublox = { version = "0.4", default-features = false }

[features]
default = ["no_std"]
no_std = ["alloc-cortex-m"]
