[env]
#FEATURES = { source = "${CARGO_MAKE_TASK_ARGS}", default_value = "[]", mapping = {"gcs" = "gcs"} }
FEATURES = "${CARGO_MAKE_TASK_ARGS}"
TOOLCHAIN = "nightly-2022-09-01"

[tasks.reboot-to-bootloader]
command = "sam"
args = ["bootloader"]
# Try to keep going, e.g. if the device already is in bootloader mode
ignore_errors = true

[tasks.build]
command = "rustup"
args = [
    "run",
    "${TOOLCHAIN}",
    "cargo",
    "build",
    "--release",
    "--features", "${FEATURES}"
]

[tasks.test]
command = "rustup"
args = [
    "run",
    "${TOOLCHAIN}",
    "cargo",
    "test",
    "--lib",
    "--target", "x86_64-unknown-linux-gnu",
    "--no-default-features"
]

[tasks.objcopy]
command = "rustup"
args = [
    "run",
    "${TOOLCHAIN}",
    "cargo",
    "objcopy",
    "--quiet",
    "--release",
    "--features", "${FEATURES}",
    "--",
    "-O", "binary",
    "target/thumbv7em-none-eabihf/release/dfu-rs.bin"
]
dependencies = ["build"]

[tasks.dfu]
linux_alias = "dfu_linux"
windows_alias = "dfu_win"

[tasks.dfu_linux]
command = "dfu-util"
args = [
    "-d", "0483:df11",
    "-a", "0",
    "-s", "0x08000000:leave",
    "-D", "target/thumbv7em-none-eabihf/release/dfu-rs.bin",
    "-w"
]
dependencies = ["objcopy", "reboot-to-bootloader"]

[tasks.dfu_win]
command = "./dfu-util.exe"
args = [
    "-d", "0483:df11",
    "-a", "0",
    "-s", "0x08000000:leave",
    "-D", "target/thumbv7em-none-eabihf/release/dfu-rs.bin",
]
dependencies = ["objcopy", "reboot-to-bootloader"]

[tasks.dfu-log]
command = "sam"
args = ["logcat"]
dependencies = ["dfu"]

[tasks.swd]
command = "rustup"
args = [
    "run",
    "${TOOLCHAIN}",
    "cargo",
    "embed",
    "--release",
    "--features", "${FEATURES}",
    "--chip=stm32f401rctx"
]
