[package]
name = "sam"
description = "Sam Ground Station"
version = "0.1.0"
edition = "2021"

[dependencies]
euroc_fc_firmware = { git = "ssh://git@gitlab.com/tudsat-rocket1/microcontrollers/flight-computers/euroc_fc_firmware.git", default-features = false }
#euroc_fc_firmware = { path = "../euroc_fc_firmware", default-features = false }
clap = { version = "3.2", features = ["derive"] }
colored = "2"
eframe = "0.19"
egui_extras = { version = "0.19", features = ["svg"] }
serde = { version = "1", features = ["derive"] }
postcard = "0.7.2"
serialport = "4"
nalgebra = "0.30"
