[package]
name = "sam"
description = "Sam Ground Station"
version = "0.1.0"
edition = "2021"

[dependencies]
euroc_fc_firmware = { git = "ssh://git@gitlab.com/tudsat-rocket1/microcontrollers/flight-computers/euroc_fc_firmware.git", default-features = false }
#euroc_fc_firmware = { path = "../euroc_fc_firmware", default-features = false }
clap = { version = "3.2", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
indicatif = "0.17"
colored = "2"
image = { version = "0.24", features = ["png"] }
eframe = { git = "https://github.com/KoffeinFlummi/egui", branch = "plot-tweaks" } # TODO: upstream this
epaint = { git = "https://github.com/KoffeinFlummi/egui", branch = "plot-tweaks" }
egui_extras = { git = "https://github.com/KoffeinFlummi/egui", branch = "plot-tweaks", features = ["image"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.89"
postcard = "1.0"
serialport = "4"
nalgebra = "0.31"
siphasher = "0.3"
chrono = "0.4"
crc = "2"
rfd = "0.10"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
home = "0.5" # No home directories in web assembly

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
wasm-logger = "0.2.0"

# The following entries are only required for web assembly compilation
[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.dev]
wasm-opt = false

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
