[package]
name = "sam"
description = "Sam Ground Station"
version = "0.1.0"
edition = "2021"

[dependencies]
mithril = { git = "https://github.com/tudsat-rocket/mithril.git", default-features = false }
#mithril = { path = "../mithril", default-features = false }
clap = { version = "3.2", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
colored = "2"
image = { version = "0.24", features = ["png"] }
egui = "0.22"
eframe = "0.22"
egui_extras = { version = "0.22", features = ["image"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.89"
postcard = "1.0"
serialport = "4"
nalgebra = "0.31"
siphasher = "0.3"
chrono = "0.4"
crc = "2"
directories = "4.0"
slippy-map-tiles = "0.16"
colorgrad = "0.6"
rand_distr = { version = "0.4", default-features = false }
tokio = "1.33"
futures = "0.3.28"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "stream", "json"] }

# Used for profiling
puffin = { version = "0.14", optional = true }
puffin_egui = { version = "0.19", optional = true }

[patch.crates-io]
egui = { git = "https://github.com/emilk/egui", rev = "d483ac47ba05311cbb2098e27f31a89450b3560f" }
eframe = { git = "https://github.com/emilk/egui", rev = "d483ac47ba05311cbb2098e27f31a89450b3560f" }
egui_extras = { git = "https://github.com/emilk/egui", rev = "d483ac47ba05311cbb2098e27f31a89450b3560f" }

# X86 dependencies
[target.'cfg(target_arch = "x86_64")'.dependencies]
rfd = "0.10"
home = "0.5" # No home directories in web assembly
indicatif = "0.17"

[target.'cfg(all(target_arch = "x86_64", not(target_os = "windows")))'.dependencies]
rand = { version = "0.8", default-features = false, features = ["small_rng", "getrandom"] }

[target.'cfg(target_os = "windows")'.dependencies]
rand = { version = "0.8", default-features = false, features = ["std", "std_rng"] }

# Android dependencies
[target.'cfg(target_arch = "aarch64")'.dependencies]
home = "0.5" # No home directories in web assembly
indicatif = "0.17"
rand = { version = "0.8", default-features = false, features = ["small_rng", "getrandom"] }

# Web Assembly dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
rand = { version = "0.8", default-features = false, features = ["small_rng"] }
web-time = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2.87"
wasm-logger = "0.2.0"

[features]
profiling = ["dep:puffin", "dep:puffin_egui"]

# The following entries are only required for web assembly compilation
[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.dev]
wasm-opt = false

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
