[workspace]
resolver = "2"
members = [
    "gui",              # Main ground control GUI
    "galadriel",        # Basic numerical rocketry simulation, used via GUI or standalone
    "state_estimator",  # State estimation used both in SITL simulations and firmware
    "shared_types",     # Types like telemetry and settings shared between firmware, simulation and GUI
]
default-members = ["gui"] # Allows running GUI by simply running `$ cargo run` in root of workspace

[workspace.dependencies]
nalgebra = { version = "0.32", features = ["macros", "mint", "serde-serialize-no-std"] }
egui = { version = "0.26", default-features = false }
eframe = { version = "0.26", default-features = false, features = ["glow", "wayland", "x11"] }
egui_plot = "0.26"
egui_extras = { version = "0.26", features = ["image"] }
