[package]
name = "archive"
description = ""
version = "0.1.0"
edition = "2021"

[dependencies]
shared_types = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
