[package]
name = "shared_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { workspace = true }
serde = { version = "1", features = ["derive"] }
postcard = "1.0"
siphasher = "0.3"
