name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_sam_native:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev libgtk-3-dev libudev-dev
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - run: cargo build
    - run: cargo test --workspace --exclude "*_firmware" --exclude sam_android

  build_sam_wasm:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
    - run: cargo install wasm-pack
    - run: wasm-pack build --target no-modules
